### ISSUE TITLE
(Feature Request) Keyboard Shortcuts

### ISSUE THREAD

**Issue by eeriemyxi** [ionStici/dictionary-web-app-fem#1]
Hi, I really liked the front-end you have here. It was minimal and elegant—just perfect during my study hours as a non-native English-medium student.

I think it would be a cool idea to add in a few shortcuts to navigate the site. What do you think? Especially one that scrolls to the top, focuses on the word search box, then selects the text that was already there—for super quick word searches.

**Comment by eeriemyxi** [comment]
I convinced Bard to make me a working userscript that would integrate a shortcut I needed the most. Though I'd say some keyboard shortcuts can still be useful to other users of the front-end, so I will be leaving the issue open from my side. Thanks for the implementation.

Here's the userscript if anybody is interested:
```js
// ==UserScript==
// @name        Clear Search Input Box on Specific Site
// @version      1.0
// @description   Selects the search input box on a specific site and clears the text already there when the Ctrl + Alt + H keybind is pressed.
// @author       Bard
// @match        *://dictionary-web-app-fem.netlify.app/
// ==/UserScript==


document.addEventListener('keydown', function(event) {
  if (event.ctrlKey && event.altKey && event.keyCode === 72) {
    var inputBox = document.querySelector('input[name="search"]');
    if (inputBox) {
      inputBox.select();
      inputBox.value = '';
      window.scrollTo(0, 0);
    }
  }
});

```

**Comment by ionStici** [comment]
Hey there! 👋 Thank you for your interest! It really made my day. 🌟
Great idea btw! I just got the feature up and running, so feel free to try it out. 👨‍💻
Wish you all the best!
